### ISSUE TITLE
second run of GitHub action to deploy changes never takes effect

### ISSUE THREAD

**Issue by jamesfalkner** [Azure-Samples/workshop-migrate-jboss-on-app-service#107]
At the end of section 4, the user creates a GitHub action to build and deploy the app, and this works fine.

But the next step, they edit some CSS to change the background color of the header, and push that code, and let the GitHub action run again to rebuild and re-deploy the app to app service.

However, the app is never updated -- the new background color never shows up, even though the action completes successfully.

**Comment by JasonFreeberg** [comment]
Note: when James restarted the web app the new background color still didn't show up
