### ISSUE TITLE
Create list of common errors/gotchas/mistakes

### ISSUE THREAD

**Issue by jamesfalkner** [Azure-Samples/workshop-migrate-jboss-on-app-service#49]
- If the .WAR deploys successfully, but the user sees the JBoss EAP landing page, then that means the app failed to start. Likely because the user did not set the connection strings to Postgres in the app settings
- Troubleshooting app startup:
    - In the Portal, go to "App Service Logs" and enable it. Then you can go to "Log Stream" and watch the startup logs.
    - On ASE, users cannot use the "App Service Logs" feature to get the logs from the web app since the site is network secured. They'll need to go to "Diagnostic Settings" and send the logs "Console Logs" and "App Logs" to a "Log Analytics Workspace".

**Comment by JasonFreeberg** [comment]
How to operate Teams breakout rooms:

1. Create rooms
   ![image](https://user-images.githubusercontent.com/18747768/141167670-5470c21f-00b8-419d-804c-2baab79fc010.png)
1.  When closing the room, make sure participants don't leave, just close the room to bring them back
