### ISSUE TITLE
GitPod instructions: mention signing up with GitHub SSO

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure-Samples/workshop-migrate-jboss-on-app-service#59]
Also, in the sign-up flow there's a prompt so the user doesn't need to do the URL-based setup flow

![image](https://user-images.githubusercontent.com/18747768/141163133-27e912ae-208c-4418-8dbb-046ff2ac909f.png)

**Comment by JasonFreeberg** [comment]
Just record screen setting this up

**Comment by danieloh30** [comment]
@JasonFreeberg I don't see this when I create an account via a Github account. Where can I find this flow and where should I need to add this in `0-environment-setup.md`? Maybe right after "Go to https://gitpod.io/ and create an account. You can use the Single-Sign-On to create a GitPod account from your GitHub account."?

**Comment by JasonFreeberg** [comment]
1. Start SSO flow with GitHub
    ![image](https://user-images.githubusercontent.com/18747768/144111469-3f201eb3-b3d9-4209-b8c9-1aff64102972.png)
2. Click "New Project"
    ![image](https://user-images.githubusercontent.com/18747768/144111588-4baa25d4-40eb-491a-b776-6cfa50132b75.png)
3. Click "Authorize"
    ![image](https://user-images.githubusercontent.com/18747768/144111656-3e0de347-13fa-4671-a2b8-836ef0494e71.png)
4. Install on your personal account
    ![image](https://user-images.githubusercontent.com/18747768/144111756-50734308-24d0-47e4-b031-35aeceac909c.png)
5. Select your fork of the migration workshop repo
    ![image](https://user-images.githubusercontent.com/18747768/144111875-0607f4c2-cbd9-4493-ab24-f56943f44f07.png)
6. Click "Install"
7. Select the project on the following screen
    ![image](https://user-images.githubusercontent.com/18747768/144112230-c596456f-56eb-4fa0-a0d0-08a20b48ac7d.png)
8. Select your personal team
    ![image](https://user-images.githubusercontent.com/18747768/144112403-b84cda9d-9b57-42d5-b058-bfd62075273f.png)
9. Click "New Workspace". This will start the build for the dev container, which will take about one minute.
    ![image](https://user-images.githubusercontent.com/18747768/144114338-d4a5740d-d26f-4467-9c6e-d9efa026a114.png)

**Comment by danieloh30** [comment]
@JasonFreeberg do you want me to add the above screenshots to "2. Go to https://gitpod.io/ and create an account. You can use the Single-Sign-On to create a GitPod account from your GitHub account."?

**Comment by JasonFreeberg** [comment]
Hey @danieloh30 I'm making a PR for the change now, I added those pictures there to keep track as I was going through it

**Comment by danieloh30** [comment]
Sounds great! Thx for doing it :)
