### ISSUE TITLE
Section 2-2

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure-Samples/workshop-migrate-jboss-on-app-service#63]
Add a sentence that the `ApplicationLifecycleListener` needs to be removed. The code snippet removes it, but the instructions do not

![image](https://user-images.githubusercontent.com/18747768/141171685-064f0db2-265d-449a-866c-257d2e04d2ec.png)

**Comment by JasonFreeberg** [comment]
There's a typo in the instructions. It says to click `ApplicationLifecycleListenerEvent` but it should be `ApplicationLifecycleEvent`

**Comment by danieloh30** [comment]
https://github.com/Azure-Samples/workshop-migrate-jboss-on-app-service/pull/71
