### ISSUE TITLE
Env setup section: tell users that they need to add "repo" access

### ISSUE THREAD

**Issue by JasonFreeberg** [Azure-Samples/workshop-migrate-jboss-on-app-service#68]
When Sandra tried to push her changes, she got a permissions error. Need to add instructions for users to go to Settings > Integrations > Edit Permissions

![image](https://user-images.githubusercontent.com/18747768/141176084-0be42d98-9494-4a01-a396-474bbd3488c8.png)

Then add "repo" permissions

![image](https://user-images.githubusercontent.com/18747768/141175726-363009d4-c4e5-4c87-a4a4-952d15134f8e.png)

**Comment by danieloh30** [comment]
PR: https://github.com/Azure-Samples/workshop-migrate-jboss-on-app-service/pull/75
