### ISSUE TITLE
Replace Adoptium by MS OpenJDK

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure-Samples/workshop-migrate-jboss-on-app-service#83]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
There are references to Adoptium , for instance at [https://github.com/Azure-Samples/workshop-migrate-jboss-on-app-service/blob/main/.gitpod.Dockerfile](https://github.com/Azure-Samples/workshop-migrate-jboss-on-app-service/blob/main/.gitpod.Dockerfile)

It would be better to replace those references with MS OpenJDK

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JasonFreeberg** [comment]
I don't believe JBoss/Wildfly has been certified with the MS build of OpenJDK. At the time we wrote the Dockerfile it wasn't.

**Comment by danieloh30** [comment]
No, we have no plan to support MS build of OpenJDK for EAP. For more information about "JBoss EAP 7.4 Supported Configurations" here - https://access.redhat.com/articles/2026253
